### ISSUE TITLE
Panic during execution of Brainfuck code

### ISSUE THREAD

**Issue by lookharm** [lookharm/go-brainfuck#1]
Description:
While executing the provided Brainfuck code snippet, a panic occurs instead of generating the expected output. The panic indicates an unexpected error or invalid state during the execution.

Code:
```go
code = `+[-->-[>>+>-----<<]<--<---]>-.>>>+.>>..+++[.>]<<<<.+++.------.<<-.>>>>+.`
output := Run(code, nil)
if string(output) != "Hello World!\n" {
 	t.FailNow()
}
```

Expected Output: "Hello World!\n"

Actual Behavior: Panic occurs during code execution

To Reproduce:
1. Use the provided code snippet in a test case.
2. Execute the test case.
3. Observe the panic message or error stack trace.

Environment:
- Operating System: Mac OS
- Go version: 1.20

**Comment by Kalam132** [comment]
The BF code shouldn't in fact execute successfully (you can try via the online interpreter [here](https://www.tutorialspoint.com/execute_brainfk_online.php)) as it is trying to move the pointer to negative values.

**Comment by lookharm** [comment]
The issue has been closed based on the reason provided by Kalam132.
